/**
 * Vendors site-kit from the sibling source directory into vendor/site-kit.
 *
 * site-kit is the single source of truth and lives at ../site-kit, but Vercel
 * uploads only this project directory, so a file:../site-kit dependency cannot
 * resolve at deploy time. Edit there, build there, then run this.
 *
 *   npm run sync:kit
 *
 * The package.json is REBUILT here rather than copied. Copying the source one
 * carries its "prepare": "npm run build" across, and npm runs prepare for a
 * file: dependency on every install: the vendored copy then tries to compile
 * itself with a tsconfig.build.json that was never vendored, npm install
 * fails, and the Vercel build dies before it starts. Ship dist and src, the
 * runtime dependencies, and nothing else.
 *
 * src/ is vendored as well as dist/ because gate:compliance runs the scanner
 * from source.
 */
import { cp, rm, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const SRC = path.resolve(process.cwd(), "..", "site-kit");
const DEST = path.resolve(process.cwd(), "vendor", "site-kit");

if (!existsSync(path.join(SRC, "dist"))) {
  console.error(`No build at ${SRC}/dist. Run "npm run build" in site-kit first.`);
  process.exit(1);
}

for (const dir of ["dist", "src"]) {
  await rm(path.join(DEST, dir), { recursive: true, force: true });
  await mkdir(path.join(DEST, dir), { recursive: true });
  await cp(path.join(SRC, dir), path.join(DEST, dir), { recursive: true });
}

const pkg = JSON.parse(await readFile(path.join(SRC, "package.json"), "utf8"));
const vendored = {
  name: pkg.name,
  version: pkg.version,
  type: pkg.type,
  license: pkg.license,
  private: true,
  description: `${pkg.description} Vendored copy, pinned to this site (CLAUDE.md 8). Generated by scripts/sync-kit.mjs, do not edit.`,
  main: pkg.main,
  types: pkg.types,
  exports: pkg.exports,
  dependencies: pkg.dependencies,
};
await writeFile(path.join(DEST, "package.json"), JSON.stringify(vendored, null, 2) + "\n");

if ("scripts" in vendored || "devDependencies" in vendored) {
  console.error("Refusing to vendor build scripts or devDependencies.");
  process.exit(1);
}
console.log(`Vendored site-kit ${pkg.version}: dist, src, no scripts, no devDependencies.`);
